name = "rumbo-aventura"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

# --- PREVIEW ---
[env.preview]
compatibility_flags = ["nodejs_compat"]

# --- PRODUCCIÃ“N ---
[env.production]
compatibility_flags = ["nodejs_compat"]